### ISSUE TITLE
Add events resource

### ISSUE THREAD

**Issue by aonomike** [AgileVentures/WebsiteOneBackendApi#11]
Create a Event model for the 
Add resources to perform CRUD operations on Events.

The fields to include are:
- name
- description
- start_date
- start_time
- duration
- category
- event_for
- project
- repeats

<img width="1185" alt="Screen Shot 2019-08-13 at 6 48 07 PM" src="https://user-images.githubusercontent.com/1543546/62956107-f87e2100-bdfa-11e9-83aa-63d28ef44039.png">

**Comment by mainangethe** [comment]
hey @aonomike , would want to work on this

**Comment by mattlindsey** [comment]
Need graphql query for a single event.  Also mutations for update and delete.  I believe the create mutation has been done already.

**Comment by mattlindsey** [comment]
I'll probably start working on this @aonomike, so I'll un-assign you and assign myself.

**Comment by mattlindsey** [comment]
Query for single event is done, so just update and delete remaining.
