### ISSUE TITLE
Add schema file

### ISSUE THREAD

**Issue by aonomike** [AgileVentures/WebsiteOneBackendApi#26]
Add the website one `schema.rb` file to this repository
## Expected Behavior

Repository has the `schema.rb` file
## Current Behavior

The repository does not have the schema.rb
## Possible Solution

Copy schema.rb from WebsiteOne
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39):
* Operating System and version (desktop or mobile):

**Comment by cesswairimu** [comment]
Hey @aonomike I can see the schema.rb file in the repo.  https://github.com/AgileVentures/WebsiteOneBackendApi/blob/develop/db/schema.rb

**Comment by aonomike** [comment]
Seems the bot did not close this ticket, Worked on it already. Thanks for letting me know :)
