### ISSUE TITLE
Add ActiveModel::Serializer gem

### ISSUE THREAD

**Issue by aonomike** [AgileVentures/WebsiteOneBackendApi#32]
Add the active model serializer gem to the repo. For the benefits and more understaning of serialiization, please [read here](https://buttercms.com/blog/json-serialization-in-rails-a-complete-guide)
## Expected Behavior

Active model serializer gem added to the repo
## Current Behavior

Active model serializer not added to the repo

**Comment by StlMaris123** [comment]
This isue is nolonger valid as we will be moving forward with [AtiveModel::Serialization](https://api.rubyonrails.org/classes/ActiveModel/Serialization.html)
