### ISSUE TITLE
Add project resource

### ISSUE THREAD

**Issue by aonomike** [AgileVentures/WebsiteOneBackendApi#35]
Add project resource with the following attributes
- name
- image_url
- description
- status
- github url
- issue tracker
- slack channel name
## Expected Behavior

JSON API endpoint for projects
## Current Behavior

No JSON API endpoint for projects

## Possible Solution

Please see this [implementation](https://github.com/AgileVentures/WebsiteOne/blob/develop/app/models/project.rb)

**Comment by riccardo-giomi** [comment]
## Plan
From @aonomike, @ethanstrominger  and @riccardo-giomi:

* Finish the update and delete request specs
* Look at @NickSchimek events specs implementation as reference
* Decide on a standard for the request specs
* Consider drying up common behaviour with a function, shared example or similar
* Create new issue to add authorization
