### ISSUE TITLE
Configure postgres credentials with env variables

### ISSUE THREAD

**Issue by mattwr18** [AgileVentures/WebsiteOneBackendApi#60]
Many developers do not use the default `postgres` username and password.
## Expected Behavior

We should provide a way to set this in our local dev and/or `.env` file
## Current Behavior

Now, you must either use the default values, or add this to the code and not push it up, to avoid code creep
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39):
* Operating System and version (desktop or mobile):

**Comment by NickSchimek** [comment]
Is it possible to simply gitignore the database.yml file?

**Comment by gr1d99** [comment]
I don't think we should `gitignore` database.yml.

If we are going to use `.env` then I think there should be a `.env.example` file that contains all required environment variables and then `gitignore` `.env` file.

With this approach, one will be required to setup their own `.env` file base on the `.env.example` file with values specific to their development environment.

**Comment by mattwr18** [comment]
hey @NickSchimek ... great to talk to you again. Congrats, by the way! 
I agree with @gr1d99 that we could just add `.env`... we have another `PR` that adds this already for `DEVISE_JWT_SECRET`... 
With this implementation https://github.com/AgileVentures/WebsiteOneBackendApi/pull/61, however, the developer can choose to use local `env` variables, or add it to a `.env` file, which will soon be in place and `.gitignore`d

**Comment by NickSchimek** [comment]
You too @mattwr18  - btw I was asking if it would be **possible** to gitignore db.yml
