### ISSUE TITLE
Set up graphql

### ISSUE THREAD

**Issue by mattwr18** [AgileVentures/WebsiteOneBackendApi#62]
Let's use GraphQL?

It's really cool! This would require refactoring the `React` app, but there are many benefits to using it over a traditional(sic) API.
## Expected Behavior

We should be able to access the backend over the GraphQL API
## Current Behavior

It's a traditional API

**Comment by ciremoussadia** [comment]
hey @mattwr18, nice to read you. What do you call traditional API?
