### ISSUE TITLE
Make develop the default branch and protected

### ISSUE THREAD

**Issue by aonomike** [AgileVentures/WebsiteOneBackendApi#7]
Currently master is the default branch. I would be nice if this was changed to `develop` and develop be protected.

**Comment by mainangethe** [comment]
Hey @aonomike , would want to set this up

**Comment by aonomike** [comment]
Hi @mattwr18 seems I dont have rights to set this up, maybe you could go ahead and set this up? @mainangethe you may need some access rights to the repo so as to set this up that you may not have at the moment. Maybe we wait for @mattwr18 's response :)

**Comment by mattwr18** [comment]
I think this is already the way you want it, no @aonomike ?
![Screenshot from 2020-03-05 10-10-30](https://user-images.githubusercontent.com/26943915/75965787-946f9700-5ec9-11ea-8b11-d4ae039507ac.png)


The default branch is `develop` and it is protected, along with `staging`, and `master`
