### ISSUE TITLE
Set up rubocop 

### ISSUE THREAD

**Issue by aonomike** [AgileVentures/WebsiteOneBackendApi#78]
We need rubocop set up in the application to help with linting. There are good documentation on how to get that set up [here](https://docs.rubocop.org/en/latest/configuration/) :)

## Expected Behavior

Rubocop catches our linting mistakes
## Current Behavior

Rubocop not yet implemented
## Possible Solution

See documentation [here](https://docs.rubocop.org/en/latest/configuration/)

**Comment by okothkongo** [comment]
@aonomike can I setup this ?
